backend:
  image: registry.relizahub.com/8c86c264-f905-42b0-9869-d6f6a6e59b8f-private/rebom-backend
  replicaCount: 1
frontend:
  image: registry.relizahub.com/8c86c264-f905-42b0-9869-d6f6a6e59b8f-private/rebom-frontend
  replicaCount: 1
postgresql:
  image: postgres:14.1
  defaultSecret: true
  replicaCount: 1
  storage: 5Gi
flyway:
  image: flyway/flyway:8.4.4-alpine
ingress:
  minimalIngressEnabled: true
  traefikEnabled: false
  host: localhost